"""Fix has_conflict_of_interest type to Boolean and rename metadata

Revision ID: 092196cbada8
Revises: 002
Create Date: 2025-11-19 13:10:27.591441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '092196cbada8'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_parsed_data_jsonb', table_name='disclosure_parsed_data', postgresql_using='gin')
    op.drop_index('ix_disclosure_parsed_data_rcept_no', table_name='disclosure_parsed_data')
    op.drop_table('disclosure_parsed_data')
    op.drop_index('idx_disclosures_corp_date', table_name='disclosures')
    op.drop_index('idx_disclosures_report_nm_trgm', table_name='disclosures', postgresql_using='gin')
    op.drop_index('idx_disclosures_stock_date', table_name='disclosures')
    op.drop_index('ix_disclosures_corp_code', table_name='disclosures')
    op.drop_index('ix_disclosures_rcept_dt', table_name='disclosures')
    op.drop_index('ix_disclosures_rcept_no', table_name='disclosures')
    op.drop_index('ix_disclosures_stock_code', table_name='disclosures')
    op.drop_table('disclosures')
    op.drop_index('idx_crawl_jobs_type_status', table_name='crawl_jobs')
    op.drop_index('ix_crawl_jobs_job_type', table_name='crawl_jobs')
    op.drop_index('ix_crawl_jobs_status', table_name='crawl_jobs')
    op.drop_index('ix_crawl_jobs_task_id', table_name='crawl_jobs')
    op.drop_table('crawl_jobs')
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('companies_ontology_object_id_key', 'companies', type_='unique')
    op.drop_constraint('companies_ticker_key', 'companies', type_='unique')
    op.drop_index('idx_company_name', table_name='companies')
    op.drop_index('idx_company_ontology', table_name='companies')
    op.create_index(op.f('ix_companies_market'), 'companies', ['market'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_ontology_object_id'), 'companies', ['ontology_object_id'], unique=True)
    op.create_index(op.f('ix_companies_sector'), 'companies', ['sector'], unique=False)
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=True)
    op.alter_column('officers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('officers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_officer_current_company', table_name='officers')
    op.drop_index('idx_officer_name', table_name='officers')
    op.drop_index('idx_officer_ontology', table_name='officers')
    op.drop_constraint('officers_ontology_object_id_key', 'officers', type_='unique')
    op.create_index(op.f('ix_officers_current_company_id'), 'officers', ['current_company_id'], unique=False)
    op.create_index(op.f('ix_officers_influence_score'), 'officers', ['influence_score'], unique=False)
    op.create_index(op.f('ix_officers_name'), 'officers', ['name'], unique=False)
    op.create_index(op.f('ix_officers_ontology_object_id'), 'officers', ['ontology_object_id'], unique=True)
    op.create_index(op.f('ix_officers_position'), 'officers', ['position'], unique=False)
    op.alter_column('ontology_links', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ontology_links', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_ontology_links_link_type'), 'ontology_links', ['link_type'], unique=False)
    op.create_index(op.f('ix_ontology_links_source_object_id'), 'ontology_links', ['source_object_id'], unique=False)
    op.create_index(op.f('ix_ontology_links_target_object_id'), 'ontology_links', ['target_object_id'], unique=False)
    op.alter_column('ontology_objects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ontology_objects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_ontology_objects_object_type'), 'ontology_objects', ['object_type'], unique=False)
    op.alter_column('risk_signals', 'detected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('risk_signals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('risk_signals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_risk_signal_ontology', table_name='risk_signals')
    op.drop_constraint('risk_signals_ontology_object_id_key', 'risk_signals', type_='unique')
    op.create_index(op.f('ix_risk_signals_ontology_object_id'), 'risk_signals', ['ontology_object_id'], unique=True)
    op.create_index(op.f('ix_risk_signals_pattern_type'), 'risk_signals', ['pattern_type'], unique=False)
    op.create_index(op.f('ix_risk_signals_risk_score'), 'risk_signals', ['risk_score'], unique=False)
    op.create_index(op.f('ix_risk_signals_severity'), 'risk_signals', ['severity'], unique=False)
    op.create_index(op.f('ix_risk_signals_status'), 'risk_signals', ['status'], unique=False)
    op.create_index(op.f('ix_risk_signals_target_company_id'), 'risk_signals', ['target_company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_signals_target_company_id'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_status'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_severity'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_risk_score'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_pattern_type'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_ontology_object_id'), table_name='risk_signals')
    op.create_unique_constraint('risk_signals_ontology_object_id_key', 'risk_signals', ['ontology_object_id'])
    op.create_index('idx_risk_signal_ontology', 'risk_signals', ['ontology_object_id'], unique=False)
    op.alter_column('risk_signals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('risk_signals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('risk_signals', 'detected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_ontology_objects_object_type'), table_name='ontology_objects')
    op.alter_column('ontology_objects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ontology_objects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_ontology_links_target_object_id'), table_name='ontology_links')
    op.drop_index(op.f('ix_ontology_links_source_object_id'), table_name='ontology_links')
    op.drop_index(op.f('ix_ontology_links_link_type'), table_name='ontology_links')
    op.alter_column('ontology_links', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ontology_links', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_officers_position'), table_name='officers')
    op.drop_index(op.f('ix_officers_ontology_object_id'), table_name='officers')
    op.drop_index(op.f('ix_officers_name'), table_name='officers')
    op.drop_index(op.f('ix_officers_influence_score'), table_name='officers')
    op.drop_index(op.f('ix_officers_current_company_id'), table_name='officers')
    op.create_unique_constraint('officers_ontology_object_id_key', 'officers', ['ontology_object_id'])
    op.create_index('idx_officer_ontology', 'officers', ['ontology_object_id'], unique=False)
    op.create_index('idx_officer_name', 'officers', ['name'], unique=False)
    op.create_index('idx_officer_current_company', 'officers', ['current_company_id'], unique=False)
    op.alter_column('officers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('officers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.drop_index(op.f('ix_companies_sector'), table_name='companies')
    op.drop_index(op.f('ix_companies_ontology_object_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_market'), table_name='companies')
    op.create_index('idx_company_ontology', 'companies', ['ontology_object_id'], unique=False)
    op.create_index('idx_company_name', 'companies', ['name'], unique=False)
    op.create_unique_constraint('companies_ticker_key', 'companies', ['ticker'])
    op.create_unique_constraint('companies_ontology_object_id_key', 'companies', ['ontology_object_id'])
    op.alter_column('companies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_table('crawl_jobs',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('job_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='작업 유형 (full, recent, company)'),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False, comment='작업 상태 (pending, running, completed, failed)'),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True, comment='작업 파라미터 (JSON)'),
    sa.Column('total_companies', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('total_disclosures', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('downloaded_documents', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('failed_downloads', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True, comment='에러 목록 (JSON)'),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True, comment='에러 메시지'),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='시작 시각'),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='완료 시각'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='생성 시각'),
    sa.Column('task_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Celery 태스크 ID'),
    sa.PrimaryKeyConstraint('id', name='crawl_jobs_pkey')
    )
    op.create_index('ix_crawl_jobs_task_id', 'crawl_jobs', ['task_id'], unique=True)
    op.create_index('ix_crawl_jobs_status', 'crawl_jobs', ['status'], unique=False)
    op.create_index('ix_crawl_jobs_job_type', 'crawl_jobs', ['job_type'], unique=False)
    op.create_index('idx_crawl_jobs_type_status', 'crawl_jobs', ['job_type', 'status'], unique=False)
    op.create_table('disclosures',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('rcept_no', sa.VARCHAR(length=14), autoincrement=False, nullable=False, comment='접수번호 (고유키)'),
    sa.Column('corp_code', sa.VARCHAR(length=8), autoincrement=False, nullable=False, comment='기업 코드'),
    sa.Column('corp_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('stock_code', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('report_nm', sa.VARCHAR(length=500), autoincrement=False, nullable=False, comment='보고서명'),
    sa.Column('rcept_dt', sa.VARCHAR(length=8), autoincrement=False, nullable=False, comment='접수일자 (YYYYMMDD)'),
    sa.Column('flr_nm', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='공시 제출인명'),
    sa.Column('rm', sa.TEXT(), autoincrement=False, nullable=True, comment='비고'),
    sa.Column('storage_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='S3/R2 문서 URL'),
    sa.Column('storage_key', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='S3/R2 객체 키'),
    sa.Column('crawled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='크롤링 시각'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='업데이트 시각'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True, comment='추가 메타데이터 (JSON)'),
    sa.ForeignKeyConstraint(['corp_code'], ['companies.corp_code'], name='disclosures_corp_code_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='disclosures_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_disclosures_stock_code', 'disclosures', ['stock_code'], unique=False)
    op.create_index('ix_disclosures_rcept_no', 'disclosures', ['rcept_no'], unique=True)
    op.create_index('ix_disclosures_rcept_dt', 'disclosures', ['rcept_dt'], unique=False)
    op.create_index('ix_disclosures_corp_code', 'disclosures', ['corp_code'], unique=False)
    op.create_index('idx_disclosures_stock_date', 'disclosures', ['stock_code', 'rcept_dt'], unique=False)
    op.create_index('idx_disclosures_report_nm_trgm', 'disclosures', ['report_nm'], unique=False, postgresql_using='gin')
    op.create_index('idx_disclosures_corp_date', 'disclosures', ['corp_code', 'rcept_dt'], unique=False)
    op.create_table('disclosure_parsed_data',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('rcept_no', sa.VARCHAR(length=14), autoincrement=False, nullable=False),
    sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='파싱된 공시 데이터'),
    sa.Column('parsed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='파싱 시각'),
    sa.Column('parser_version', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='파서 버전'),
    sa.Column('sections_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True, comment='섹션 수'),
    sa.Column('tables_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True, comment='테이블 수'),
    sa.ForeignKeyConstraint(['rcept_no'], ['disclosures.rcept_no'], name='disclosure_parsed_data_rcept_no_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='disclosure_parsed_data_pkey')
    )
    op.create_index('ix_disclosure_parsed_data_rcept_no', 'disclosure_parsed_data', ['rcept_no'], unique=True)
    op.create_index('idx_parsed_data_jsonb', 'disclosure_parsed_data', ['parsed_data'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
