"""Add cb_subscribers table

Revision ID: e4f697667073
Revises: 161765c6c15b
Create Date: 2025-11-19 21:34:17.065322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4f697667073'
down_revision: Union[str, None] = '161765c6c15b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False, comment='작업 유형 (full, recent, company)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='작업 상태 (pending, running, completed, failed)'),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='작업 파라미터 (JSON)'),
    sa.Column('total_companies', sa.Integer(), nullable=True),
    sa.Column('total_disclosures', sa.Integer(), nullable=True),
    sa.Column('downloaded_documents', sa.Integer(), nullable=True),
    sa.Column('failed_downloads', sa.Integer(), nullable=True),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='에러 목록 (JSON)'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='에러 메시지'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='시작 시각'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='완료 시각'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성 시각'),
    sa.Column('task_id', sa.String(length=100), nullable=True, comment='Celery 태스크 ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crawl_jobs_type_status', 'crawl_jobs', ['job_type', 'status'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_job_type'), 'crawl_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_status'), 'crawl_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_task_id'), 'crawl_jobs', ['task_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('disclosures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rcept_no', sa.String(length=14), nullable=False, comment='접수번호 (고유키)'),
    sa.Column('corp_code', sa.String(length=8), nullable=False),
    sa.Column('corp_name', sa.String(length=200), nullable=False),
    sa.Column('stock_code', sa.String(length=6), nullable=True),
    sa.Column('report_nm', sa.String(length=500), nullable=False, comment='보고서명'),
    sa.Column('rcept_dt', sa.String(length=8), nullable=False, comment='접수일자 (YYYYMMDD)'),
    sa.Column('flr_nm', sa.String(length=200), nullable=True, comment='공시 제출인명'),
    sa.Column('rm', sa.Text(), nullable=True, comment='비고'),
    sa.Column('storage_url', sa.String(length=500), nullable=True, comment='S3/R2 문서 URL'),
    sa.Column('storage_key', sa.String(length=500), nullable=True, comment='S3/R2 객체 키'),
    sa.Column('crawled_at', sa.DateTime(), nullable=False, comment='크롤링 시각'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='업데이트 시각'),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='추가 메타데이터 (JSON)'),
    sa.ForeignKeyConstraint(['corp_code'], ['companies.corp_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_disclosures_corp_date', 'disclosures', ['corp_code', 'rcept_dt'], unique=False)
    op.create_index('idx_disclosures_report_nm_trgm', 'disclosures', ['report_nm'], unique=False, postgresql_using='gin', postgresql_ops={'report_nm': 'gin_trgm_ops'})
    op.create_index('idx_disclosures_stock_date', 'disclosures', ['stock_code', 'rcept_dt'], unique=False)
    op.create_index(op.f('ix_disclosures_corp_code'), 'disclosures', ['corp_code'], unique=False)
    op.create_index(op.f('ix_disclosures_rcept_dt'), 'disclosures', ['rcept_dt'], unique=False)
    op.create_index(op.f('ix_disclosures_rcept_no'), 'disclosures', ['rcept_no'], unique=True)
    op.create_index(op.f('ix_disclosures_stock_code'), 'disclosures', ['stock_code'], unique=False)
    op.create_table('cb_subscribers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cb_id', sa.UUID(), nullable=False),
    sa.Column('subscriber_name', sa.String(length=500), nullable=False, comment='인수자명 (개인/법인)'),
    sa.Column('subscriber_type', sa.String(length=50), nullable=True, comment='인수자 유형 (개인/법인/기관)'),
    sa.Column('relationship_to_company', sa.String(length=200), nullable=True, comment='회사 또는 최대주주와의 관계'),
    sa.Column('is_related_party', sa.String(length=10), nullable=True, comment='특수관계자 여부 (Y/N)'),
    sa.Column('selection_rationale', sa.Text(), nullable=True, comment='선정 경위'),
    sa.Column('transaction_history', sa.Text(), nullable=True, comment='발행결정 전후 6월 이내 거래내역'),
    sa.Column('subscription_amount', sa.Float(), nullable=True, comment='인수 금액 (원)'),
    sa.Column('subscription_quantity', sa.Float(), nullable=True, comment='인수 수량'),
    sa.Column('notes', sa.Text(), nullable=True, comment='비고'),
    sa.Column('source_disclosure_id', sa.String(length=20), nullable=True, comment='출처 공시 번호 (rcept_no)'),
    sa.Column('source_date', sa.String(length=8), nullable=True, comment='출처 공시 일자 (YYYYMMDD)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cb_id'], ['convertible_bonds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cb_subscribers_cb_id', 'cb_subscribers', ['cb_id'], unique=False)
    op.create_index('idx_cb_subscribers_name', 'cb_subscribers', ['subscriber_name'], unique=False)
    op.create_index('idx_cb_subscribers_related', 'cb_subscribers', ['is_related_party'], unique=False)
    op.create_index('idx_cb_subscribers_source', 'cb_subscribers', ['source_disclosure_id'], unique=False)
    op.create_index(op.f('ix_cb_subscribers_cb_id'), 'cb_subscribers', ['cb_id'], unique=False)
    op.create_index(op.f('ix_cb_subscribers_subscriber_name'), 'cb_subscribers', ['subscriber_name'], unique=False)
    op.create_table('disclosure_parsed_data',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rcept_no', sa.String(length=14), nullable=False),
    sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='파싱된 공시 데이터'),
    sa.Column('parsed_at', sa.DateTime(), nullable=False, comment='파싱 시각'),
    sa.Column('parser_version', sa.String(length=20), nullable=True, comment='파서 버전'),
    sa.Column('sections_count', sa.Integer(), nullable=True, comment='섹션 수'),
    sa.Column('tables_count', sa.Integer(), nullable=True, comment='테이블 수'),
    sa.ForeignKeyConstraint(['rcept_no'], ['disclosures.rcept_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rcept_no')
    )
    op.create_index('idx_parsed_data_jsonb', 'disclosure_parsed_data', ['parsed_data'], unique=False, postgresql_using='gin')
    op.alter_column('affiliates', 'parent_company_id',
               existing_type=sa.UUID(),
               comment='모회사 ID',
               existing_nullable=False)
    op.alter_column('affiliates', 'affiliate_company_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment='계열사 ID')
    op.alter_column('affiliates', 'affiliate_name',
               existing_type=sa.VARCHAR(length=200),
               comment='계열사명',
               existing_nullable=False)
    op.alter_column('affiliates', 'business_number',
               existing_type=sa.VARCHAR(length=20),
               comment='사업자등록번호',
               existing_nullable=True)
    op.alter_column('affiliates', 'relationship_type',
               existing_type=sa.VARCHAR(length=50),
               comment='관계 유형 (subsidiary, affiliate, etc.)',
               existing_nullable=True)
    op.alter_column('affiliates', 'is_listed',
               existing_type=sa.BOOLEAN(),
               comment='상장 여부',
               existing_nullable=True)
    op.alter_column('affiliates', 'ownership_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='지분율 (%)',
               existing_nullable=True)
    op.alter_column('affiliates', 'voting_rights_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='의결권 비율 (%)',
               existing_nullable=True)
    op.alter_column('affiliates', 'total_assets',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='총자산',
               existing_nullable=True)
    op.alter_column('affiliates', 'revenue',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='매출액',
               existing_nullable=True)
    op.alter_column('affiliates', 'net_income',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='순이익',
               existing_nullable=True)
    op.alter_column('affiliates', 'source_disclosure_id',
               existing_type=sa.VARCHAR(length=36),
               comment='출처 공시 ID',
               existing_nullable=True)
    op.alter_column('affiliates', 'source_date',
               existing_type=sa.VARCHAR(length=8),
               comment='기준일자 (YYYYMMDD)',
               existing_nullable=True)
    op.alter_column('affiliates', 'properties',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='추가 정보 (JSON)',
               existing_nullable=True)
    op.alter_column('convertible_bonds', 'company_id',
               existing_type=sa.UUID(),
               comment='발행 회사 ID',
               existing_nullable=False)
    op.alter_column('convertible_bonds', 'bond_name',
               existing_type=sa.VARCHAR(length=200),
               comment='채권명 (예: 제1회 무보증 사모 전환사채)',
               existing_nullable=True)
    op.alter_column('convertible_bonds', 'bond_type',
               existing_type=sa.VARCHAR(length=50),
               comment='채권 유형 (CB, BW, EB 등)',
               existing_nullable=True)
    op.alter_column('convertible_bonds', 'issue_date',
               existing_type=sa.DATE(),
               comment='발행일',
               existing_nullable=True)
    op.alter_column('convertible_bonds', 'maturity_date',
               existing_type=sa.DATE(),
               comment='만기일',
               existing_nullable=True)
    op.alter_column('convertible_bonds', 'issue_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='발행금액 (원)',
               existing_nullable=True)
    op.alter_column('convertible_bonds', 'interest_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='이자율 (%)',
               existing_nullable=True)
    op.alter_column('convertible_bonds', 'conversion_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='전환가액 (원)',
               existing_nullable=True)
    op.alter_column('convertible_bonds', 'conversion_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='전환비율 (%)',
               existing_nullable=True)
    op.alter_column('convertible_bonds', 'conversion_start_date',
               existing_type=sa.DATE(),
               comment='전환 청구 개시일',
               existing_nullable=True)
    op.alter_column('convertible_bonds', 'conversion_end_date',
               existing_type=sa.DATE(),
               comment='전환 청구 종료일',
               existing_nullable=True)
    op.alter_column('convertible_bonds', 'redemption_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='상환가액',
               existing_nullable=True)
    op.alter_column('convertible_bonds', 'early_redemption_date',
               existing_type=sa.DATE(),
               comment='조기상환일',
               existing_nullable=True)
    op.alter_column('convertible_bonds', 'outstanding_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='잔존금액',
               existing_nullable=True)
    op.alter_column('convertible_bonds', 'converted_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='전환된 금액',
               existing_nullable=True)
    op.alter_column('convertible_bonds', 'redeemed_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='상환된 금액',
               existing_nullable=True)
    op.alter_column('convertible_bonds', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='상태 (active, converted, redeemed)',
               existing_nullable=True)
    op.alter_column('convertible_bonds', 'source_disclosure_id',
               existing_type=sa.VARCHAR(length=36),
               comment='출처 공시 ID',
               existing_nullable=True)
    op.alter_column('convertible_bonds', 'source_date',
               existing_type=sa.VARCHAR(length=8),
               comment='기준일자 (YYYYMMDD)',
               existing_nullable=True)
    op.alter_column('convertible_bonds', 'properties',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='추가 정보 (JSON)',
               existing_nullable=True)
    op.create_index(op.f('ix_convertible_bonds_issue_date'), 'convertible_bonds', ['issue_date'], unique=False)
    op.create_index(op.f('ix_convertible_bonds_maturity_date'), 'convertible_bonds', ['maturity_date'], unique=False)
    op.create_index(op.f('ix_convertible_bonds_status'), 'convertible_bonds', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_convertible_bonds_status'), table_name='convertible_bonds')
    op.drop_index(op.f('ix_convertible_bonds_maturity_date'), table_name='convertible_bonds')
    op.drop_index(op.f('ix_convertible_bonds_issue_date'), table_name='convertible_bonds')
    op.alter_column('convertible_bonds', 'properties',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='추가 정보 (JSON)',
               existing_nullable=True)
    op.alter_column('convertible_bonds', 'source_date',
               existing_type=sa.VARCHAR(length=8),
               comment=None,
               existing_comment='기준일자 (YYYYMMDD)',
               existing_nullable=True)
    op.alter_column('convertible_bonds', 'source_disclosure_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='출처 공시 ID',
               existing_nullable=True)
    op.alter_column('convertible_bonds', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='상태 (active, converted, redeemed)',
               existing_nullable=True)
    op.alter_column('convertible_bonds', 'redeemed_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='상환된 금액',
               existing_nullable=True)
    op.alter_column('convertible_bonds', 'converted_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='전환된 금액',
               existing_nullable=True)
    op.alter_column('convertible_bonds', 'outstanding_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='잔존금액',
               existing_nullable=True)
    op.alter_column('convertible_bonds', 'early_redemption_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='조기상환일',
               existing_nullable=True)
    op.alter_column('convertible_bonds', 'redemption_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='상환가액',
               existing_nullable=True)
    op.alter_column('convertible_bonds', 'conversion_end_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='전환 청구 종료일',
               existing_nullable=True)
    op.alter_column('convertible_bonds', 'conversion_start_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='전환 청구 개시일',
               existing_nullable=True)
    op.alter_column('convertible_bonds', 'conversion_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='전환비율 (%)',
               existing_nullable=True)
    op.alter_column('convertible_bonds', 'conversion_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='전환가액 (원)',
               existing_nullable=True)
    op.alter_column('convertible_bonds', 'interest_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='이자율 (%)',
               existing_nullable=True)
    op.alter_column('convertible_bonds', 'issue_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='발행금액 (원)',
               existing_nullable=True)
    op.alter_column('convertible_bonds', 'maturity_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='만기일',
               existing_nullable=True)
    op.alter_column('convertible_bonds', 'issue_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='발행일',
               existing_nullable=True)
    op.alter_column('convertible_bonds', 'bond_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='채권 유형 (CB, BW, EB 등)',
               existing_nullable=True)
    op.alter_column('convertible_bonds', 'bond_name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='채권명 (예: 제1회 무보증 사모 전환사채)',
               existing_nullable=True)
    op.alter_column('convertible_bonds', 'company_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='발행 회사 ID',
               existing_nullable=False)
    op.alter_column('affiliates', 'properties',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='추가 정보 (JSON)',
               existing_nullable=True)
    op.alter_column('affiliates', 'source_date',
               existing_type=sa.VARCHAR(length=8),
               comment=None,
               existing_comment='기준일자 (YYYYMMDD)',
               existing_nullable=True)
    op.alter_column('affiliates', 'source_disclosure_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='출처 공시 ID',
               existing_nullable=True)
    op.alter_column('affiliates', 'net_income',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='순이익',
               existing_nullable=True)
    op.alter_column('affiliates', 'revenue',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='매출액',
               existing_nullable=True)
    op.alter_column('affiliates', 'total_assets',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='총자산',
               existing_nullable=True)
    op.alter_column('affiliates', 'voting_rights_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='의결권 비율 (%)',
               existing_nullable=True)
    op.alter_column('affiliates', 'ownership_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='지분율 (%)',
               existing_nullable=True)
    op.alter_column('affiliates', 'is_listed',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='상장 여부',
               existing_nullable=True)
    op.alter_column('affiliates', 'relationship_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='관계 유형 (subsidiary, affiliate, etc.)',
               existing_nullable=True)
    op.alter_column('affiliates', 'business_number',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='사업자등록번호',
               existing_nullable=True)
    op.alter_column('affiliates', 'affiliate_name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='계열사명',
               existing_nullable=False)
    op.alter_column('affiliates', 'affiliate_company_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment=None,
               existing_comment='계열사 ID')
    op.alter_column('affiliates', 'parent_company_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='모회사 ID',
               existing_nullable=False)
    op.drop_index('idx_parsed_data_jsonb', table_name='disclosure_parsed_data', postgresql_using='gin')
    op.drop_table('disclosure_parsed_data')
    op.drop_index(op.f('ix_cb_subscribers_subscriber_name'), table_name='cb_subscribers')
    op.drop_index(op.f('ix_cb_subscribers_cb_id'), table_name='cb_subscribers')
    op.drop_index('idx_cb_subscribers_source', table_name='cb_subscribers')
    op.drop_index('idx_cb_subscribers_related', table_name='cb_subscribers')
    op.drop_index('idx_cb_subscribers_name', table_name='cb_subscribers')
    op.drop_index('idx_cb_subscribers_cb_id', table_name='cb_subscribers')
    op.drop_table('cb_subscribers')
    op.drop_index(op.f('ix_disclosures_stock_code'), table_name='disclosures')
    op.drop_index(op.f('ix_disclosures_rcept_no'), table_name='disclosures')
    op.drop_index(op.f('ix_disclosures_rcept_dt'), table_name='disclosures')
    op.drop_index(op.f('ix_disclosures_corp_code'), table_name='disclosures')
    op.drop_index('idx_disclosures_stock_date', table_name='disclosures')
    op.drop_index('idx_disclosures_report_nm_trgm', table_name='disclosures', postgresql_using='gin', postgresql_ops={'report_nm': 'gin_trgm_ops'})
    op.drop_index('idx_disclosures_corp_date', table_name='disclosures')
    op.drop_table('disclosures')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_crawl_jobs_task_id'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_status'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_job_type'), table_name='crawl_jobs')
    op.drop_index('idx_crawl_jobs_type_status', table_name='crawl_jobs')
    op.drop_table('crawl_jobs')
    # ### end Alembic commands ###
